version: '3'
services:
  nextjs:
    container_name: Formify
    entrypoint: yarn start:prod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3458:3458'
    depends_on:
      - postgres

  postgres:
    container_name: Postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'

