version: '3'
services:
  nextjs:
    container_name: Formify
    entrypoint: yarn start:prod
    restart: always
    environment:
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
      - CLERK_SECRET_KEY=$CLERK_SECRET_KEY
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3458:3458'
    depends_on:
      - postgres

  postgres:
    container_name: Postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - '5432:5432'

