name: CI

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
  prepare-environment:
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Stop and remove containers, networks
        run: |
          if docker ps -a | grep formify ; then
            docker rm -f formify
          else
            echo "Container formify does not exist"
          fi
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    env:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - name: docker-compose
        run: |
          docker-compose build \
          --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY} \
          --build-arg CLERK_SECRET_KEY=${CLERK_SECRET_KEY} \
          --build-arg DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/postgres?schema=public
          docker-compose up -d
